### ISSUE TITLE
Discussion about immutability

### ISSUE THREAD

**Issue by Deleplace** [elliotchance/pie#104]
It's great that Pie methods are "safe" because they never alter the receiver, and always allocate new data instead.

The adjective "immutable" is maybe not the best to describe the slice types, as they are always mutable.

One solution would be to change the wording and make it extra-explicit that the objects are ot immutable.

Another solution would be to enforce immutability by generating struct types with private fields :
```
type Cars {
    cars []Car
}

func (ss Cars) Len() int {
    return len(ss.cars)
}

func (ss Cars) Index(i int) Car {
    return ss.cars[i]
}
```
This would add some code and some complexity in the Pie project. But also, users would lose the flexibility and convenience of using a `Cars` directly everywhere a `[]Car`is expected.

**Comment by elliotchance** [comment]
They are still mutable, people will just update their package code to manipulate `.cars` internally since it's not in a separate package. Also, they will actually have to do that if they add they own methods to the type as well. I think it's important that casting is between types is easy because I do that a lot. We could just update the language in the README:

4. Functions never modify inputs. Unlike some built-ins such as `sort.Strings`.

It's a bit nitpicky because Go doesn't have any concept of immutability, except for constants which can only be scalars, and therefore cannot apply here. I think it's safe to assume that a user doesn't think we changed the fundamentals of the language to get the library working.

**Comment by Deleplace** [comment]
Go doesn't provide much indeed for immutability. Strings are immutable, which is nice. Private fields indeed are immutable outside the package, and mutable inside (so it depends if we want Pie to protect the authors of packages using Pie, or the end users of these packages).

**Comment by elliotchance** [comment]
I understand what you mean, but I don't think this change is beneficial.
