### ISSUE TITLE
Functions table in README

### ISSUE THREAD

**Issue by Deleplace** [elliotchance/pie#105]
The type `Maps` stands out, as it is a bit special. I initially thought it was for types in the form `[]map[KeyType][ElementType]` like the 3 previous columns on the left.

![Capture d’écran 2019-05-05 à 17 56 14](https://user-images.githubusercontent.com/13508141/57196657-457e6b80-6f5f-11e9-9873-8ceadf005cdf.png)

It is however for _generating methods Keys and Values to a type in the form map[KeyType][ElementType]_, thus the receiver is actually not a slice type.

I suggest we split this table into 2 distinct tables, for clarity.

**Comment by elliotchance** [comment]
I want to overhaul this completely - I'm just not sure how yet. I don't like how we have double enter documentation (between the actual function comments and the README) as well as the fact that the README only contains a subset of the documentation which will confuse people.

Either we remove all function comments and just put the documentation once, for each function in the README. Or we link functions to godoc.org.

I like having the table of comparisons because it also highlights which functions are missing to be created. The reason the Maps column looks so light is that a lot of those functions just haven't been implemented yet. `All` is one example from your screenshot.

**Comment by DylanMeeus** [comment]
Honestly the table is a pretty great thing. 

It gave me an overview of the available functions at a glance, and also an idea of what it does. I did not see the table as a complete documentation of how the function works, but rather as a concise overview. So it did not confuse me to see more details in the function itself. 

On the other hand, if I ran into an error (cause of passing a nil somewhere where I should not), it would be helpful to find full documentation of that function. 

Perhaps it is overkill, but we might be able to generate such a readme based on the function comments? So we can still have the entries in the table and link to the full documentation.

**Comment by elliotchance** [comment]
We can definitely generate the README, as I have done for projects before. However, if this is the case there is no need to have the documentation on the function as well. It might as well be documented directly into the README and not require a generation step.
