### ISSUE TITLE
Undefined method

### ISSUE THREAD

**Issue by hiepndd** [elliotchance/pie#110]
Hi @elliotchance,
Anyone could tell me what step am I missing when run `go generate ./... && go install && go generate ./...`? 
List error attached below
<img width="1054" alt="Screen Shot 2019-05-07 at 4 39 05 PM" src="https://user-images.githubusercontent.com/23348270/57290253-39bdb100-70e7-11e9-880a-b1b570edd94d.png">
Thanks in advance!

**Comment by DylanMeeus** [comment]
It's not something I've encountered.
Can you run
`go generate ./...` in the root directory of the project, and see what the output is like? 

I'm assuming that's the failing step, you'll probably notice that in the `pie/pie/` directory, you have no `*_pie.go` files?

**Comment by hiepndd** [comment]
Hi @DylanMeeus,
I run it in the root directory of the project

**Comment by DylanMeeus** [comment]
Hey @hiepndd

Do you have the `_pie.go` files in the `pie` directory as well? My guess is that those are not there. 
If not, I suspect it's indeed the generate command that is failing. Can you run the command seperately to see if `go generate` or `go install` is failing?

**Comment by hiepndd** [comment]
Hi @DylanMeeus,
checked, but when I ran `go generate ./... && go install && go generate ./...`. It's auto delete those func in image above :(

**Comment by elliotchance** [comment]
I hit this often when the project was newer. Since we are generating code from code, the binary that's installed will always be one step behind so you will get stuck in an infinite loop of errors because they depend on each other.

1. Clean your working directory (stash or reset).
2. `go get -u github.com/elliotchance/pie` to fix your binary.
3. Now you should be able to run `go generate ./... && go install && go generate ./...` after you make changes.

**Comment by hiepndd** [comment]
Hi all,
Fixed 
thanks, guys
