### ISSUE TITLE
ToStrings -> StringsUsing

### ISSUE THREAD

**Issue by elliotchance** [elliotchance/pie#124]
StringsUsing is a more consistent naming for what it does.

**Comment by DylanMeeus** [comment]
Might I suggest something akin to `MapString`? 
Because we have `Map`, and this function effectively is a Map where the outcome is known to be a `String`. It's effectively a special case of Map where the result is `String`.

mh.. though `MapString` might make it sound like you map _from_ `String` rather than to `String`. `MapToString` is a bit more verbose but does show what it does.

This is just a random idea, feel free to ignore it completely :sweat_smile:

**Comment by elliotchance** [comment]
It's always fun to see how someone's mind works through a problem. I also do that a lot with my comments. :)
