### ISSUE TITLE
generate for custom types

### ISSUE THREAD

**Issue by ghostsquad** [elliotchance/pie#16]
This is all about type safety, it would make sense then to be able to generate all these functions (and more) for any given type. If this makes sense, I might try to contribute a PR with this

**Comment by elliotchance** [comment]
What are you thinking?

**Comment by ghostsquad** [comment]
Something like this:
https://godoc.org/github.com/ahmetb/go-linq

but type-safe

**Comment by ghostsquad** [comment]
@elliotchance here's my first take on some example usage:

---

## Custom Types - Generated Code

```go
//go:generate piegen -destination=person_pie.go -package=person -self_package=github.com/elliotchance/examples/person
package person

// + PieBake
type Person struct {
	First string
	Last  string
}

func (p *Person) String() string {
   return fmt.Sprintf("%s %s - %d", p.First, p.Last, p.Age)
}

// + PieBake
type BakePersonToString func(p Person) string
```

_Notice the comments above each type. This is how PieGen discovers types & transformations_

The generated code from this would allow you to do the following:

```go
p := PersonPie{
	Values: []*Person{
		&Person{
			First: "leonhard",
			Last:  "euler",
			Age: 57,
		},
		&Person{
			First: "sophie",
			Last: "germain",
			Age: 45
		},
		&Person{
			First: "mary",
			Last: "jackson",
			Age: 30,
		}
	}
}

selected := p.Where(func(p Person) bool {
	return len(p.First) > 4
}).First().Done()

fmt.Printf("%v\n", selected.First)
// leonhard euler - 57

even:= p.Where(func(p Person) bool {
	return p.Age % 2 == 0
}).Done()

fmt.Printf("%v\n", even)
// [mary jackson - 30]

names := p.BakePersonToString(func (p Person) string {
	return p.First
}).Done()

fmt.Printf("%v\n", names)
// [leonhard sophie mary]
```

Each method may return a `Pie`, `Bite`, or `Bake` struct, each of which has slightly different behavior.

`Pie`'s are slices
`Bite`'s are single elements
`Bake`'s allow specific transformations, such as `func (p Person) string`, kind of like a `Select` in [go-linq](https://godoc.org/github.com/ahmetb/go-linq#Query.Select)

These structs allow chaining, and nothing executes until you call `Done()` at end.

**Comment by elliotchance** [comment]
I understand what you mean now. However, I don't want the scope of the project to go in this direction. I'd rather keep as a simple plug-and-play.

I think the furthest I would want to take it is to use reflection for an initial transform, like:

```go
pie.ToStrings(func (p *Person) string {
    return p.First
}).

// From here it's just normal pie.Strings.
    Transform(strings.ToUpper)
```

Even that is pushing the boundary a bit because we cannot ensure at compile time that `*Person` would be correct.

**Comment by ghostsquad** [comment]
As you wish!

**Comment by elliotchance** [comment]
You're right. This is actually a good idea, now that I've had some time to think about it. As I go through some of my code that could be replaced it's just impossible to limit it to the static types already defined.

Here is what I've come up with: https://github.com/elliotchance/pie/blob/e40030da0e6d696a059f9aed84f652771ab22283. Very crude, most code is deleted for now. The basics are:

1. Using `go generate` attaching functionality to an existing type is easy. This creates/replaces a file called `ints_pie.go`:

```go
//go:generate pie Ints
type Ints []int
```

2. There are potentially many functions. I don't want to bloat the executable and code completion if the user is only interested in one or a few functions. This also may have an effect on code coverage. So they should be able to specify only several methods:

```go
//go:generate pie Foos.Contains.Reverse
type Foos []Foo
```

3. It's neat to have the `//go:generate` with each type, but it could be located anywhere and describe many types:

```go
//go:generate pie Foos.Contains.Reverse BarCollection.Only
```

4. Notice that the `pie` package is actually an executable now. There is no need for a separate `piegen`. The code is actually in vanilla Go (so it can be understood by IDEs): https://github.com/elliotchance/pie/blob/e40030da0e6d696a059f9aed84f652771ab22283/pie.go

This file (or others) is actually a template in itself: https://github.com/elliotchance/pie/commit/e40030da0e6d696a059f9aed84f652771ab22283#diff-7ddfb3e035b42cd70649cc33393fe32cR51

The `SliceType` and `ElementType` are replaced for the output file. They are defined as placeholders in `main.go`.

5. Right now it uses the whole template. However, not all functions will work with all types. For example `Sum` will only work with numeric types so I'll have to add some logic that AST parses the input file and removes functions that would otherwise cause a compilation error. This is actually fairly trivial. Apart from IDEs understanding the template it gives me godoc.org to point to as well.

6. There are other functions with the comparison and transforms. Not sure what I'm going to do with those right now but off the top of my head they could work the same way.

7. The CI build will use the same existing tests, but we can add new ones for a custom type. It simply has to run `go generate` before `go test`.

8. The real power of this is maps. We can use the same technique to generate common functions for maps of any type as well. That is for another discussion though.

What do you think?

**Comment by ghostsquad** [comment]
@elliotchance can you create a PR so it's easier to see these changes? Is there something here you want me to work on?

**Comment by elliotchance** [comment]
I have merged the smallest iteration and tagged it as v2.0.0. This only supports numeric types and `string`. I didn't want to blow out the size of the change.

Right now, the best thing you can do to help is to try it. If you discover any bugs or which to add a feature then a PR is always welcome.

I am currently working on it to add custom types.

**Comment by elliotchance** [comment]
v2.1.0 now supports custom types! Go crazy 😄
