### ISSUE TITLE
func Mode() SliceType

### ISSUE THREAD

**Issue by elliotchance** [elliotchance/pie#68]
Mode returns the most frequent value. If there are multiple modes then one of them is returned. However, this is not intended to be deterministic. It is best to only use this when you know there to be a single most frequent value, or multiple modes are permitted.

**Comment by DylanMeeus** [comment]
Might I suggest to just return all the values for the mode instead of a single one?
I don't see the harm in returning a slice. This is the way that python (with scipy) does it as well, so for people used to stats packages in other languages this should not be unfamiliar.

I also believe it's more correct to return all of them. As a user of "mode", I'd expect it to return all of them and not a single one - leading me to believe that the other values occur _less_ frequently.

**Comment by elliotchance** [comment]
Sure, that’s fair.

**Comment by DylanMeeus** [comment]
I'll "claim" this one and implement it ;-)
